### ISSUE TITLE
Configs please, and make it 1.21.x and not 1.21.1 forced

### ISSUE THREAD

**Issue by GuyFromTheInternet** [TheFaceJD/NoCoordinates#4]
In a config I recommend you letting people choose what item should act as an compass and in which world each compass would work
by default the config will have the compass and the recovery compass, the compass only allowed in the overworld, and the recovery compass only in the nether and the end, also it being 1.21.x instead of purely 1.21.1 would be nice, since they didnt change much

**Comment by TheFaceJD** [comment]
I consider it unnecessary to add a config. 

I will release support for several versions soon.

**Comment by TheFaceJD** [comment]
New version has been added
