### ISSUE TITLE
Suggestion: Option for coordinates in all dimensions with any compass type

### ISSUE THREAD

**Issue by NerdSkape** [TheFaceJD/NoCoordinates#5]
I completely understand why a recovery compass is needed for the end and nether. It makes 100% from a lore perspective, but it would be nice to have to option to use any compass in any dimension. Inventory is already an issue in Minecraft and it would be nice not having to carry and extra compass around for other dimensions or having to switch every time dimensions are changed. 

Having the option for either play style would be great.

**Comment by TheFaceJD** [comment]
At present, the modification is implemented on the **client** side. This implies that my modification solely eliminates lines from the debug menu, as well as displays a notification when the compass is held.

The addition of similar settings to a modification implies that if your companions also possess this modification installed, they too will be required to configure it.

I am currently exploring various avenues to address this issue. At present, I have formulated **two strategies** for resolving this conundrum.
**1:** 
   Developing a novel modification that incorporates several novel compasses: the Hell's Compass, the End's Compass, and the Universal Compass. Each of these compasses will be crafted using unique materials available within these dimensions.
**2:**
   Revise the functionality of the existing modification:
now a default compass will work everywhere. The only problem with this is the violation of the lore.


**I will also be glad to hear your ideas and suggestions.**

**Comment by NerdSkape** [comment]
As a player who wants to be lazy, I'm in favor of option 2. From a lore perspective option 1 is 100% the better choice.

A challenge I've had with the current implementation needing a specific compass (aka the recovery compass) is even though I've found several large deep dark biomes, I have been unlucky in finding an ancient city for the echo shards to craft the recovery compass. I'm approaching day 400 in the world and have entered the nether long ago. Moving and linking portals without coords was a pain and waiting to find echo shards to craft the recovery compass made the lack of coords go from challenging and immersive to annoying and unfun. Making the Hell's compass more accessible than echo shards would be a nice change. 

While requiring a recovery compass is a good idea, it has not been ideal for this play through. Going with option one and requiring a special compass requiring materials from that dimension would probably solve the issue I am having with obtaining the materials to craft a recovery compass. Needing all three compasses to craft the Universal Compass also makes a lot of sense, 

Depending on how the crafting/upgrade process works, the End's compass might have very little use since I would imagine at that point you would quickly replace it with the Universal Compass. It may make more sense to make the Universal Compass be the end compass.

**Comment by TheFaceJD** [comment]
Thank you for your feedback. I will use it in the next version of the mod.  I will be working on a new compass mod in the near future. 

If you still have any ideas related to the mod for new compasses or the NoCoordinates, I will be glad to hear them.
